Traceback (most recent call last):
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jthow\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ruta = r'/Users/instructorzamora/Documents/3_Maestria_Estadistica_UNINORTE/3_Tercer_Semestre/Machine_Learning/tornados.csv.zip'  
df = pd.read_csv(ruta)
df.isnull().sum()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m ruta [38;5;241m=[39m [38;5;124mr[39m[38;5;124m'[39m[38;5;124m/Users/instructorzamora/Documents/3_Maestria_Estadistica_UNINORTE/3_Tercer_Semestre/Machine_Learning/tornados.csv.zip[39m[38;5;124m'[39m  
[1;32m----> 2[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_csv[49m[43m([49m[43mruta[49m[43m)[49m
[0;32m      3[0m df[38;5;241m.[39misnull()[38;5;241m.[39msum()

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py:948[0m, in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)[0m
[0;32m    935[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[0;32m    936[0m     dialect,
[0;32m    937[0m     delimiter,
[1;32m   (...)[0m
[0;32m    944[0m     dtype_backend[38;5;241m=[39mdtype_backend,
[0;32m    945[0m )
[0;32m    946[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[1;32m--> 948[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py:611[0m, in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    608[0m _validate_names(kwds[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mnames[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m))
[0;32m    610[0m [38;5;66;03m# Create the parser.[39;00m
[1;32m--> 611[0m parser [38;5;241m=[39m TextFileReader(filepath_or_buffer, [38;5;241m*[39m[38;5;241m*[39mkwds)
[0;32m    613[0m [38;5;28;01mif[39;00m chunksize [38;5;129;01mor[39;00m iterator:
[0;32m    614[0m     [38;5;28;01mreturn[39;00m parser

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py:1448[0m, in [0;36mTextFileReader.__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m   1445[0m     [38;5;28mself[39m[38;5;241m.[39moptions[[38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m] [38;5;241m=[39m kwds[[38;5;124m"[39m[38;5;124mhas_index_names[39m[38;5;124m"[39m]
[0;32m   1447[0m [38;5;28mself[39m[38;5;241m.[39mhandles: IOHandles [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m-> 1448[0m [38;5;28mself[39m[38;5;241m.[39m_engine [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_engine[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mengine[49m[43m)[49m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\parsers\readers.py:1705[0m, in [0;36mTextFileReader._make_engine[1;34m(self, f, engine)[0m
[0;32m   1703[0m     [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m mode:
[0;32m   1704[0m         mode [38;5;241m+[39m[38;5;241m=[39m [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m
[1;32m-> 1705[0m [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;241m=[39m [43mget_handle[49m[43m([49m
[0;32m   1706[0m [43m    [49m[43mf[49m[43m,[49m
[0;32m   1707[0m [43m    [49m[43mmode[49m[43m,[49m
[0;32m   1708[0m [43m    [49m[43mencoding[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mencoding[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[0;32m   1709[0m [43m    [49m[43mcompression[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mcompression[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[0;32m   1710[0m [43m    [49m[43mmemory_map[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mmemory_map[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[43m,[49m
[0;32m   1711[0m [43m    [49m[43mis_text[49m[38;5;241;43m=[39;49m[43mis_text[49m[43m,[49m
[0;32m   1712[0m [43m    [49m[43merrors[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mencoding_errors[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mstrict[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m,[49m
[0;32m   1713[0m [43m    [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moptions[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mstorage_options[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m,[49m
[0;32m   1714[0m [43m[49m[43m)[49m
[0;32m   1715[0m [38;5;28;01massert[39;00m [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m   1716[0m f [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mhandles[38;5;241m.[39mhandle

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\common.py:784[0m, in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    779[0m [38;5;66;03m# ZIP Compression[39;00m
[0;32m    780[0m [38;5;28;01melif[39;00m compression [38;5;241m==[39m [38;5;124m"[39m[38;5;124mzip[39m[38;5;124m"[39m:
[0;32m    781[0m     [38;5;66;03m# error: Argument 1 to "_BytesZipFile" has incompatible type[39;00m
[0;32m    782[0m     [38;5;66;03m# "Union[str, BaseBuffer]"; expected "Union[Union[str, PathLike[str]],[39;00m
[0;32m    783[0m     [38;5;66;03m# ReadBuffer[bytes], WriteBuffer[bytes]]"[39;00m
[1;32m--> 784[0m     handle [38;5;241m=[39m _BytesZipFile(
[0;32m    785[0m         handle, ioargs[38;5;241m.[39mmode, [38;5;241m*[39m[38;5;241m*[39mcompression_args  [38;5;66;03m# type: ignore[arg-type][39;00m
[0;32m    786[0m     )
[0;32m    787[0m     [38;5;28;01mif[39;00m handle[38;5;241m.[39mbuffer[38;5;241m.[39mmode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m:
[0;32m    788[0m         handles[38;5;241m.[39mappend(handle)

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\io\common.py:1027[0m, in [0;36m_BytesZipFile.__init__[1;34m(self, file, mode, archive_name, **kwargs)[0m
[0;32m   1024[0m kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mcompression[39m[38;5;124m"[39m, zipfile[38;5;241m.[39mZIP_DEFLATED)
[0;32m   1025[0m [38;5;66;03m# error: Incompatible types in assignment (expression has type "ZipFile",[39;00m
[0;32m   1026[0m [38;5;66;03m# base class "_BufferedWriter" defined the type as "BytesIO")[39;00m
[1;32m-> 1027[0m [38;5;28mself[39m[38;5;241m.[39mbuffer: zipfile[38;5;241m.[39mZipFile [38;5;241m=[39m zipfile[38;5;241m.[39mZipFile(  [38;5;66;03m# type: ignore[assignment][39;00m
[0;32m   1028[0m     file, mode, [38;5;241m*[39m[38;5;241m*[39mkwargs
[0;32m   1029[0m )

File [1;32m~\miniconda3\envs\ml_venv\lib\zipfile.py:1250[0m, in [0;36mZipFile.__init__[1;34m(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)[0m
[0;32m   1248[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[0;32m   1249[0m     [38;5;28;01mtry[39;00m:
[1;32m-> 1250[0m         [38;5;28mself[39m[38;5;241m.[39mfp [38;5;241m=[39m [43mio[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[43mfilemode[49m[43m)[49m
[0;32m   1251[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[0;32m   1252[0m         [38;5;28;01mif[39;00m filemode [38;5;129;01min[39;00m modeDict:

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/instructorzamora/Documents/3_Maestria_Estadistica_UNINORTE/3_Tercer_Semestre/Machine_Learning/tornados.csv.zip'

